# Generated by Django 3.2.6 on 2021-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'NEW'), ('In Progress', 'IN PROGRESS'), ('Complete', 'COMPLETE')], default='New', max_length=50),
        ),
    ]
