# Generated by Django 3.2.6 on 2021-08-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mark_complete',
            field=models.BooleanField(default=False),
        ),
    ]
